### PR TITLE
refactor: polish homepage style

### PR DESCRIPTION
**Pull request by Peefy**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [x] N
- [ ] Y 

refactor: polish homepage style

#### 2. What is the scope of this PR (e.g. component or file name):

+ src/pages/index.module.css
+ indes.js

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

refactor: polish homepage style

+ Before

image

+ After

image
image

Reference: [Color Names](https://www.color-hex.com/color-names.html)

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [x] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by amyXia1994** [comment]
I consult the designer of kusionstack logo and he suggests using `#1677ff`(the antgroup's officially used theme color). And here's the result if you may consider about it:
image

image

**Comment by Peefy** [comment]
> and please check the color of links and Hidden symbols: image

fixed.

**Comment by Peefy** [comment]
> please change the corresponding css in dark theme:
> 
> image

fixed

**Comment by Peefy** [comment]
> and please check the color of links and Hidden symbols: image

fixed.

**Review by amyXia1994 — APPROVED** [review]
lgtm

p.s. the header is still in green-color schemes, maybe we could change it to blue schemes later.

image

**Pull request merged**
