### PR TITLE
Home Page edit for docs website

### PR DESCRIPTION
**Pull request by ekjotsinghmakhija**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references:

- [X] N
- [ ] Y 

#### 2. What is the scope of this PR (e.g. component or file name):
There was a lot of spacing, spelling mistake, I have improved the Home Page text to make it more professional plus appealing to developer and companies.
This is likely to increase their interaction with website and more potential of using our product and services.

Before:
Screenshot from 2024-07-26 21-41-12

After the Changes were made:
Screenshot from 2024-07-26 21-42-12

This was main highlight as other small changes that use improved sentences of the words being used 

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [X] Affects user behaviors
- [X] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [X] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
This Release changes the HomePage of website and improves the language, indentation and tone of website, making it more appealing to developers and businesses.
```

### CODE REVIEW

**Comment by ekjotsinghmakhija** [comment]
@SparkYuan I'm unable to make to publish my pull request.

**Comment by ekjotsinghmakhija** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by SparkYuan — APPROVED** [review]
lgtm

**Comment by SparkYuan** [comment]
@ekjotsinghmakhija Thanks for your contribution, welcome to our community!

**Pull request merged**
