### PR TITLE
add code-city usecase

### PR DESCRIPTION
**Pull request by SparkYuan**
add code-city usecase

### CODE REVIEW

**Comment by SparkYuan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SparkYuan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SparkYuan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SparkYuan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ldxdl** [comment]
lgtm

**Review by ldxdl — APPROVED** [review]

**Pull request merged**
