### PR TITLE
add new kusionstack blog and pdf

### PR DESCRIPTION
**Pull request by SparkYuan**

### CODE REVIEW

**Comment by chai2010** [comment]
mv pdf to https://github.com/KusionStack/community

**Comment by SparkYuan** [comment]
> mv pdf to https://github.com/KusionStack/community


https://github.com/KusionStack/community/pull/37

**Comment by chai2010** [comment]
image file size is too large, pls reduce the size (<100KB)

**Review by elliotxx — APPROVED** [review]
lgtm

**Pull request merged**
